pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('npm install') {
      steps {
        sh 'npm install'
        sh 'npm --version'
      }
    }
  }
}
